# Generated by Django 3.2.12 on 2022-04-01 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('created_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
