# Generated by Django 3.2.12 on 2022-04-15 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0002_auto_20220404_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='user_id',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='user_id',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='companies',
            name='bin',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departments',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies_app.companies'),
        ),
        migrations.AddField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies_app.companies'),
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
