# Generated by Django 3.2.12 on 2022-04-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0006_alter_staff_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
