# Generated by Django 3.2.12 on 2022-04-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0007_alter_staff_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='bin',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
