# Generated by Django 3.2.12 on 2022-04-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0010_auto_20220425_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.IntegerField(choices=[(0, 'Emp'), (1, 'Owner')]),
        ),
    ]
