# Generated by Django 3.2.13 on 2022-05-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0011_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.IntegerField(choices=[(1, 'Personal'), (2, 'Corp'), (2, 'Emp')]),
        ),
    ]
