# Generated by Django 3.2.13 on 2022-05-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0012_alter_staff_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='department',
            new_name='dep',
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.IntegerField(choices=[(1, 'Personal'), (2, 'Corp'), (3, 'Emp')]),
        ),
    ]
