# Generated by Django 3.2.13 on 2022-05-11 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0013_auto_20220509_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dep', to='companies_app.departments'),
        ),
    ]
